with_orient: false
invert_y: false
start_hl: true
hl_only: false
speed: 0.30
diag_period_sec: 0.5
cache_dir: "./.cf_cache"

drones:
  - id: "cf3"
    uri: "radio://0/80/2M/E7E7E7E703"
    ns: "/cf3"
    mocap_topic: "/mocap/cf3/pose"
    
